# Generated by Django 5.2 on 2025-05-13 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_draft_image_loginlog_template_user_delete_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='user_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
