# Generated by Django 5.2 on 2025-06-02 11:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("template_id", models.AutoField(primary_key=True, serialize=False)),
                ("tech_name", models.CharField(max_length=200)),
                ("tech_description", models.TextField()),
                ("problem_solved", models.TextField()),
                ("tech_differentiation", models.TextField()),
                ("application_field", models.TextField(blank=True, null=True)),
                ("components_functions", models.TextField()),
                ("implementation_example", models.TextField()),
                ("drawing_description", models.TextField(blank=True, null=True)),
                ("application_info", models.CharField(max_length=100)),
                ("inventor_info", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("template_title", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "user_code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("user_pw", models.CharField(max_length=200)),
                ("user_email", models.EmailField(blank=True, max_length=50, null=True)),
                ("user_phone", models.BigIntegerField(blank=True, null=True)),
                ("user_nickname", models.CharField(max_length=10)),
                ("user_privilege", models.IntegerField(default=2)),
                ("user_create_date", models.DateTimeField(auto_now_add=True)),
                ("user_left_date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                ("image_id", models.AutoField(primary_key=True, serialize=False)),
                ("image_url", models.CharField(max_length=3000)),
                ("image_name", models.CharField(max_length=3000)),
                ("image_extension", models.CharField(max_length=10)),
                (
                    "template_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assist.template",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Draft",
            fields=[
                ("draft_id", models.AutoField(primary_key=True, serialize=False)),
                ("version", models.CharField(default="v0", max_length=8)),
                ("draft_name", models.CharField(max_length=30)),
                ("create_draft", models.TextField()),
                ("create_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "draft_title",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "template_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assist.template",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="template",
            name="user_code",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assist.user",
            ),
        ),
        migrations.CreateModel(
            name="LoginLog",
            fields=[
                ("log_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_ip", models.CharField(blank=True, max_length=20, null=True)),
                ("login_time", models.DateTimeField(auto_now_add=True)),
                ("logout_time", models.DateTimeField(blank=True, null=True)),
                (
                    "user_code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="assist.user"
                    ),
                ),
            ],
        ),
    ]
